/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 tshirt_final2.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function TSHIRT(props) {
  const { nodes, materials } = useGLTF("/tshirt_final2.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes["31"].geometry} material={materials.stripes} />
      <mesh geometry={nodes["64"].geometry} material={materials.stripes} />
      <mesh geometry={nodes["70"].geometry} material={materials.stripes} />
      <mesh geometry={nodes["28"].geometry} material={materials.stripes} />
    </group>
  );
}

useGLTF.preload("/tshirt_final2.glb");
