/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 tshirt_final.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tshirt_final.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.StitchMatShape_127574.geometry} material={materials.Material109415} />
      <mesh geometry={nodes.StitchMatShape_128590.geometry} material={materials['Material109415.001']} />
      <mesh geometry={nodes.StitchMatShape_129132.geometry} material={materials['Material109415.002']} />
      <mesh geometry={nodes.StitchMatShape_130377.geometry} material={materials['Material109415.003']} />
      <mesh geometry={nodes.StitchMatShape_130648.geometry} material={materials['Material109415.004']} />
      <mesh geometry={nodes.StitchMatShape_130909.geometry} material={materials['Material109415.005']} />
      <mesh geometry={nodes.StitchMatShape_132157.geometry} material={materials['Material109415.006']} />
      <mesh geometry={nodes.Pattern2D_2949190_1.geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
      <mesh geometry={nodes.Pattern2D_2949190_2.geometry} material={materials['Knit_Fleece_Terry_FRONT_109192.001']} />
      <mesh geometry={nodes.Pattern2D_2949190_3.geometry} material={materials['Knit_Fleece_Terry_FRONT_109192.002']} />
      <mesh geometry={nodes['30_1'].geometry} material={materials['Knit_Fleece_Terry_FRONT_109192.003']} />
      <mesh geometry={nodes['30_2'].geometry} material={materials['Knit_Fleece_Terry_FRONT_109192.004']} />
      <mesh geometry={nodes['30_3'].geometry} material={materials['Knit_Fleece_Terry_FRONT_109192.005']} />
      <mesh geometry={nodes['31_1'].geometry} material={materials['Knit_Fleece_Terry_FRONT_109192.006']} />
      <mesh geometry={nodes['31_2'].geometry} material={materials['Knit_Fleece_Terry_FRONT_109192.007']} />
      <mesh geometry={nodes['31_3'].geometry} material={materials['Knit_Fleece_Terry_FRONT_109192.008']} />
      <mesh geometry={nodes['64_1'].geometry} material={materials['Knit_Fleece_Terry_FRONT_109192.009']} />
      <mesh geometry={nodes['64_2'].geometry} material={materials['Knit_Fleece_Terry_FRONT_109192.010']} />
      <mesh geometry={nodes['64_3'].geometry} material={materials['Knit_Fleece_Terry_FRONT_109192.011']} />
      <mesh geometry={nodes['70_1'].geometry} material={materials['Knit_Fleece_Terry_FRONT_109192.012']} />
      <mesh geometry={nodes['70_2'].geometry} material={materials['Knit_Fleece_Terry_FRONT_109192.013']} />
      <mesh geometry={nodes['70_3'].geometry} material={materials['Knit_Fleece_Terry_FRONT_109192.014']} />
      <mesh geometry={nodes['71_1'].geometry} material={materials['Knit_Fleece_Terry Copy 1_FRONT_109203']} />
      <mesh geometry={nodes['71_2'].geometry} material={materials['Knit_Fleece_Terry Copy 1_FRONT_109203.001']} />
      <mesh geometry={nodes['71_3'].geometry} material={materials['Knit_Fleece_Terry Copy 1_FRONT_109203.002']} />
      <mesh geometry={nodes['28_1'].geometry} material={materials['Knit_Fleece_Terry_FRONT_109192.015']} />
      <mesh geometry={nodes['28_2'].geometry} material={materials['Knit_Fleece_Terry_FRONT_109192.016']} />
      <mesh geometry={nodes['28_3'].geometry} material={materials['Knit_Fleece_Terry_FRONT_109192.017']} />
      <mesh geometry={nodes['29_1'].geometry} material={materials['Knit_Fleece_Terry Copy 1_FRONT_109203.003']} />
      <mesh geometry={nodes['29_2'].geometry} material={materials['Knit_Fleece_Terry Copy 1_FRONT_109203.004']} />
      <mesh geometry={nodes['29_3'].geometry} material={materials['Knit_Fleece_Terry Copy 1_FRONT_109203.005']} />
      <mesh geometry={nodes.Pattern2D_4474558_1.geometry} material={materials['Knit_Fleece_Terry Copy 1_FRONT_109203.006']} />
      <mesh geometry={nodes.Pattern2D_4474558_2.geometry} material={materials['Knit_Fleece_Terry Copy 1_FRONT_109203.007']} />
      <mesh geometry={nodes.Pattern2D_4474558_3.geometry} material={materials['Knit_Fleece_Terry Copy 1_FRONT_109203.008']} />
      <mesh geometry={nodes.Pattern2D_4491756_1.geometry} material={materials['Knit_Fleece_Terry Copy 1_FRONT_109203.009']} />
      <mesh geometry={nodes.Pattern2D_4491756_2.geometry} material={materials['Knit_Fleece_Terry Copy 1_FRONT_109203.010']} />
      <mesh geometry={nodes.Pattern2D_4491756_3.geometry} material={materials['Knit_Fleece_Terry Copy 1_FRONT_109203.011']} />
    </group>
  )
}

useGLTF.preload('/tshirt_final.glb')
