/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 shirt.glb 
Author: mohsenmousavi2313 (https://sketchfab.com/mohsenmousavi2313)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shirt-and-vest-97c6c77cbf8847749e13ef65cc8b4313
Title: Shirt And Vest
*/

import React, { useRef } from "react";
import {
  DragControls,
  Edges,
  Image,
  PerspectiveCamera,
  RenderTexture,
  useGLTF,
} from "@react-three/drei";
import { DoubleSide } from "three";

export function Shirt(props) {
  const { nodes, materials } = useGLTF("/shirt3.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.vest_vest2_0.geometry}
          material={materials.vest2}
        />
        <mesh geometry={nodes.vest_vest1_0.geometry}>
          <meshPhysicalMaterial>
            <RenderTexture
              attach="map"
              generateMipmaps
              height={400}
              width={400}
            >
              <PerspectiveCamera
                makeDefault
                manual
                aspect={1 / 1}
                position={[0, 0, 3]}
              />
              <color attach="background" args={["orange"]} />

              <DragControls>
                <Image
                  url="/123.png"
                  opacity={1}
                  side={DoubleSide}
                  segments={1}
                >
                  <Edges
                    linewidth={3}
                    scale={1.01}
                    threshold={15}
                    color="blue"
                  />
                </Image>
              </DragControls>
            </RenderTexture>
          </meshPhysicalMaterial>
        </mesh>
        <mesh
          geometry={nodes.buttom3_buttom_0.geometry}
          material={materials.buttom}
        />
        <mesh
          geometry={nodes.buttom4_buttom_0.geometry}
          material={materials.buttom}
        />
        <mesh
          geometry={nodes.buttom5_buttom_0.geometry}
          material={materials.buttom}
        />
        <mesh
          geometry={nodes.buttom6_buttom_0.geometry}
          material={materials.buttom}
        />
        <mesh
          geometry={nodes.buttom2_buttom_0.geometry}
          material={materials.buttom}
        />
        <mesh
          geometry={nodes.buttom1_buttom_0.geometry}
          material={materials.buttom}
        />
        <mesh
          geometry={nodes.Packet1_Packet_0.geometry}
          material={materials.Packet}
        />
        <mesh
          geometry={nodes.Packet2_Packet_0.geometry}
          material={materials.Packet}
        />
        <mesh
          geometry={nodes.back1_Packet_0.geometry}
          material={materials.Packet}
        />
        <mesh
          geometry={nodes.back2_buttom_0.geometry}
          material={materials.buttom}
        />
        <mesh
          geometry={nodes.Tshirt1_shirt_0.geometry}
          material={materials.shirt}
        />
        <mesh
          geometry={nodes.Tsgirt4_shirt_0.geometry}
          material={materials.shirt}
        />
        <mesh
          geometry={nodes.Tshirt3_shirt_0.geometry}
          material={materials.shirt}
        />
        <mesh
          geometry={nodes.CRV_CR_0.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Tshirt2_shirt_0.geometry}
          material={materials.shirt}
        />
        <mesh
          geometry={nodes.CRB_CR_0.geometry}
          material={materials.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/shirt2.glb");
