/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 shirt4.glb 
*/

import React, { useRef } from "react";

import {
  DragControls,
  Edges,
  Image,
  PerspectiveCamera,
  RenderTexture,
  useGLTF,
} from "@react-three/drei";

export function Shirt4(props) {
  const { nodes, materials } = useGLTF("/shirt4.glb");
  return (
    <group {...props} dispose={null} rotation={[0, Math.PI, 0]}>
      <mesh
        geometry={nodes.back1_Packet_0.geometry}
        material={materials.Packet}
      />
      <mesh
        geometry={nodes.back2_buttom_0.geometry}
        material={materials.buttom}
      />
      <mesh
        geometry={nodes.buttom1_buttom_0.geometry}
        material={materials.buttom}
      />
      <mesh
        geometry={nodes.buttom2_buttom_0.geometry}
        material={materials.buttom}
      />
      <mesh
        geometry={nodes.buttom3_buttom_0.geometry}
        material={materials.buttom}
      />
      <mesh
        geometry={nodes.buttom4_buttom_0.geometry}
        material={materials.buttom}
      />
      <mesh
        geometry={nodes.buttom5_buttom_0.geometry}
        material={materials.buttom}
      />
      <mesh
        geometry={nodes.buttom6_buttom_0.geometry}
        material={materials.buttom}
      />
      <mesh geometry={nodes.CRB_CR_0.geometry} material={materials.material} />
      <mesh geometry={nodes.CRV_CR_0.geometry} material={materials.material} />
      <mesh
        geometry={nodes.Packet1_Packet_0.geometry}
        material={materials.Packet}
      />
      <mesh
        geometry={nodes.Packet2_Packet_0.geometry}
        material={materials.Packet}
      />
      <mesh
        geometry={nodes.Tsgirt4_shirt_0.geometry}
        material={materials.shirt}
      />
      <mesh
        geometry={nodes.Tshirt1_shirt_0.geometry}
        material={materials.shirt}
      />
      <mesh
        geometry={nodes.Tshirt2_shirt_0.geometry}
        material={materials.shirt}
      />
      <mesh
        geometry={nodes.Tshirt3_shirt_0.geometry}
        material={materials.shirt}
      />
      <mesh geometry={nodes.vest_vest1_0.geometry}>
        <meshPhysicalMaterial>
          <RenderTexture
            attach="map"
            generateMipmaps
            height={400}
            width={400}

            // anisotropy={16}
          >
            <PerspectiveCamera
              makeDefault
              manual
              aspect={1 / 1}
              position={[0, 0, 3]}
            />
            <color attach="background" args={["orange"]} />

            <DragControls>
              <Image url="/123.png" opacity={1} segments={1}>
                <Edges
                  linewidth={3}
                  scale={1.01}
                  threshold={15} // Display edges only when the angle between two faces exceeds this value (default=15 degrees)
                  color="blue"
                />
              </Image>
            </DragControls>
          </RenderTexture>
        </meshPhysicalMaterial>
      </mesh>
      <mesh geometry={nodes.vest_vest2_0.geometry} material={materials.vest2} />
    </group>
  );
}

useGLTF.preload("/shirt4.glb");
