/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 t-shirt_t_pose.glb 
Author: Reallusion (https://sketchfab.com/reallusion)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/t-shirt-t-pose-20fbb246bd19402c82e01d7541a72f8e
Title: T-shirt T Pose
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";

export function Tshirt3() {
  const [show, setShow] = useState(false);
  const modelref = useRef();
  const { nodes, materials } = useGLTF("/t-shirt_t_pose.glb");
  console.log(modelref.current);
  return (
    <>
      <group
        dispose={null}
        ref={modelref}
        onPointerDown={() => setShow(true)}
        position={[0, 0, 0]}
      >
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.T_shirt}
          rotation={[-Math.PI / 2, 0, 0]}
        ></mesh>
      </group>
      {show && <boxHelper args={[modelref.current, 0xff8657]} />}
    </>
  );
}

useGLTF.preload("/t-shirt_t_pose.glb");
