/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 tee.glb 
*/

import React, { useEffect, useRef, useState } from "react";
import { Decal, useGLTF, useTexture } from "@react-three/drei";
import {
  MeshBasicMaterial,
  MeshPhysicalMaterial,
  MeshStandardMaterial,
  Vector3,
} from "three";

import * as THREE from "three";

export function TEE(props) {
  const { nodes, materials } = useGLTF("/tee.glb");

  const [show, setShow] = useState(false);

  const decalRef = useRef();

  const updatePos = (p) => {
    console.log(p);
    console.log("before", p);
    mesh.current.worldToLocal(p);
    console.log("after", p);

    setShow(true);

    decalRef.current.position.set(p.x, p.y, p.z);
  };
  console.log(props);
  const texture = new MeshPhysicalMaterial({ map: props.map });

  var geometry = new THREE.PlaneGeometry(10, 10, 20, 20);
  // geometry.vertices.forEach((v) => {
  //   v.z = Math.cos(v.x) * Math.sin(-v.y * 0.5) * 0.5;
  // });
  // geometry.computeFaceNormals();
  // geometry.computeVertexNormals();

  var mesh = new THREE.Mesh(
    geometry,
    new THREE.MeshStandardMaterial({
      map: props.map,
      metalness: 0.25,
      roughness: 0.25,
    })
  );

  return (
    <>
      <group {...props} dispose={null}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.Pattern2D_2949190_1.geometry}
            material={materials.Knit_Fleece_Terry_FRONT_109192}
          ></mesh>
          <mesh
            geometry={nodes.Pattern2D_2949190_2.geometry}
            material={materials["Knit_Fleece_Terry_FRONT_109192.001"]}
          />
          <mesh
            geometry={nodes.Pattern2D_2949190_3.geometry}
            material={materials["Knit_Fleece_Terry_FRONT_109192.002"]}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes["30_1"].geometry}
            material={materials["Knit_Fleece_Terry_FRONT_109192.003"]}
          />
          <mesh
            geometry={nodes["30_2"].geometry}
            material={materials["Knit_Fleece_Terry_FRONT_109192.004"]}
          />
          <mesh
            geometry={nodes["30_3"].geometry}
            material={materials["Knit_Fleece_Terry_FRONT_109192.005"]}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes["31_1"].geometry}
            material={materials["Knit_Fleece_Terry_FRONT_109192.006"]}
          />
          <mesh
            geometry={nodes["31_2"].geometry}
            material={materials["Knit_Fleece_Terry_FRONT_109192.007"]}
          />
          <mesh
            geometry={nodes["31_3"].geometry}
            material={materials["Knit_Fleece_Terry_FRONT_109192.008"]}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes["64_1"].geometry}
            material={materials["Knit_Fleece_Terry_FRONT_109192.009"]}
          />
          <mesh
            geometry={nodes["64_2"].geometry}
            material={materials["Knit_Fleece_Terry_FRONT_109192.010"]}
          />
          <mesh
            geometry={nodes["64_3"].geometry}
            material={materials["Knit_Fleece_Terry_FRONT_109192.011"]}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          {/* <mesh
            geometry={nodes["70_1"].geometry}
            material={materials["Knit_Fleece_Terry_FRONT_109192.012"]}
            ref={mesh}
          ></mesh> */}
          <mesh geometry={nodes["70_1"].geometry} material={texture}></mesh>
          <mesh
            geometry={nodes["70_2"].geometry}
            material={materials["Knit_Fleece_Terry_FRONT_109192.013"]}
          />
          <mesh
            geometry={nodes["70_3"].geometry}
            material={materials["Knit_Fleece_Terry_FRONT_109192.014"]}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes["71_1"].geometry}
            material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203"]}
          />
          <mesh
            geometry={nodes["71_2"].geometry}
            material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203.001"]}
          />
          <mesh
            geometry={nodes["71_3"].geometry}
            material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203.002"]}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes["28_1"].geometry}
            material={materials["Knit_Fleece_Terry_FRONT_109192.015"]}
          />
          <mesh
            geometry={nodes["28_2"].geometry}
            material={materials["Knit_Fleece_Terry_FRONT_109192.016"]}
          />
          <mesh
            geometry={nodes["28_3"].geometry}
            material={materials["Knit_Fleece_Terry_FRONT_109192.017"]}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes["29_1"].geometry}
            material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203.003"]}
          />
          <mesh
            geometry={nodes["29_2"].geometry}
            material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203.004"]}
          />
          <mesh
            geometry={nodes["29_3"].geometry}
            material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203.005"]}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.Pattern2D_4474558_1.geometry}
            material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203.006"]}
          />
          <mesh
            geometry={nodes.Pattern2D_4474558_2.geometry}
            material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203.007"]}
          />
          <mesh
            geometry={nodes.Pattern2D_4474558_3.geometry}
            material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203.008"]}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.Pattern2D_4491756_1.geometry}
            material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203.009"]}
          />
          <mesh
            geometry={nodes.Pattern2D_4491756_2.geometry}
            material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203.010"]}
          />
          <mesh
            geometry={nodes.Pattern2D_4491756_3.geometry}
            material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203.011"]}
          />
        </group>
        <mesh
          geometry={nodes.StitchMatShape_127574.geometry}
          material={materials.Material109415}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.StitchMatShape_128590.geometry}
          material={materials["Material109415.001"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.StitchMatShape_129132.geometry}
          material={materials["Material109415.002"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.StitchMatShape_130377.geometry}
          material={materials["Material109415.003"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.StitchMatShape_130648.geometry}
          material={materials["Material109415.004"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.StitchMatShape_130909.geometry}
          material={materials["Material109415.005"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.StitchMatShape_132157.geometry}
          material={materials["Material109415.006"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
      </group>
    </>
    // <>
    //   <primitive object={mesh} />
    // </>
  );
}

useGLTF.preload("/tee.glb");
