/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 tee6.glb 
*/

import React, { useRef } from "react";
import {
  DragControls,
  Edges,
  Image,
  PerspectiveCamera,
  PivotControls,
  RenderTexture,
  TransformControls,
  useGLTF,
} from "@react-three/drei";

export function Tee6(props) {
  const { nodes, materials } = useGLTF("/tee6.glb");
  return (
    <group {...props} dispose={null}>
      {/* <mesh
        geometry={nodes.StitchMatShape_127574.geometry}
        material={materials["Material109415.007"]}
      />
      <mesh
        geometry={nodes.StitchMatShape_128590.geometry}
        material={materials["Material109415.008"]}
      />
      <mesh
        geometry={nodes.StitchMatShape_129132.geometry}
        material={materials["Material109415.009"]}
      />
      <mesh
        geometry={nodes.StitchMatShape_130377.geometry}
        material={materials["Material109415.010"]}
      />
      <mesh
        geometry={nodes.StitchMatShape_130648.geometry}
        material={materials["Material109415.011"]}
      />
      <mesh
        geometry={nodes.StitchMatShape_130909.geometry}
        material={materials["Material109415.012"]}
      />
      <mesh
        geometry={nodes.StitchMatShape_132157.geometry}
        material={materials["Material109415.013"]}
      />
      <mesh
        geometry={nodes.Pattern2D_2949190001.geometry}
        material={materials["Knit_Fleece_Terry_FRONT_109192.018"]}
      />
      <mesh
        geometry={nodes.Pattern2D_2949190001_1.geometry}
        material={materials["Knit_Fleece_Terry_FRONT_109192.019"]}
      />
      <mesh
        geometry={nodes.Pattern2D_2949190001_2.geometry}
        material={materials["Knit_Fleece_Terry_FRONT_109192.020"]}
      />
      <mesh
        geometry={nodes["30001"].geometry}
        material={materials["Knit_Fleece_Terry_FRONT_109192.021"]}
      />
      <mesh
        geometry={nodes["30001_1"].geometry}
        material={materials["Knit_Fleece_Terry_FRONT_109192.022"]}
      />
      <mesh
        geometry={nodes["30001_2"].geometry}
        material={materials["Knit_Fleece_Terry_FRONT_109192.023"]}
      />
      <mesh
        geometry={nodes["31001"].geometry}
        material={materials["Knit_Fleece_Terry_FRONT_109192.024"]}
      />
      <mesh
        geometry={nodes["31001_1"].geometry}
        material={materials["Knit_Fleece_Terry_FRONT_109192.025"]}
      />
      <mesh
        geometry={nodes["31001_2"].geometry}
        material={materials["Knit_Fleece_Terry_FRONT_109192.026"]}
      />
      <mesh
        geometry={nodes["64001"].geometry}
        material={materials["Knit_Fleece_Terry_FRONT_109192.027"]}
      />
      <mesh
        geometry={nodes["64001_1"].geometry}
        material={materials["Knit_Fleece_Terry_FRONT_109192.028"]}
      />
      <mesh
        geometry={nodes["64001_2"].geometry}
        material={materials["Knit_Fleece_Terry_FRONT_109192.029"]}
      /> */}
      <mesh
        geometry={nodes["70001"].geometry}
        material={materials["Knit_Fleece_Terry_FRONT_109192.030"]}
      >
        <meshPhysicalMaterial>
          <RenderTexture
            attach="map"
            generateMipmaps
            height={400}
            width={400}
            // anisotropy={16}
          >
            <PerspectiveCamera
              makeDefault
              manual
              aspect={1 / 1}
              position={[0, 0, 3]}
            />
            <color attach="background" args={["orange"]} />

            <DragControls>
              <Image
                url="/123.png"
                opacity={1}
                // side={DoubleSide}
                segments={1}
              >
                <Edges
                  linewidth={3}
                  scale={1.01}
                  threshold={15} // Display edges only when the angle between two faces exceeds this value (default=15 degrees)
                  color="blue"
                />
              </Image>
            </DragControls>
          </RenderTexture>
        </meshPhysicalMaterial>
      </mesh>
      {/* <mesh
        geometry={nodes["70001_1"].geometry}
        material={materials["Knit_Fleece_Terry_FRONT_109192.031"]}
      />
      <mesh
        geometry={nodes["70001_2"].geometry}
        material={materials["Knit_Fleece_Terry_FRONT_109192.032"]}
      /> */}
      {/* <mesh
        geometry={nodes["71001"].geometry}
        material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203.012"]}
      />
      <mesh
        geometry={nodes["71001_1"].geometry}
        material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203.013"]}
      />
      <mesh
        geometry={nodes["71001_2"].geometry}
        material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203.014"]}
      />
      <mesh
        geometry={nodes["28001"].geometry}
        material={materials["Knit_Fleece_Terry_FRONT_109192.033"]}
      />
      <mesh
        geometry={nodes["28001_1"].geometry}
        material={materials["Knit_Fleece_Terry_FRONT_109192.034"]}
      />
      <mesh
        geometry={nodes["28001_2"].geometry}
        material={materials["Knit_Fleece_Terry_FRONT_109192.035"]}
      />
      <mesh
        geometry={nodes["29001"].geometry}
        material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203.015"]}
      />
      <mesh
        geometry={nodes["29001_1"].geometry}
        material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203.016"]}
      />
      <mesh
        geometry={nodes["29001_2"].geometry}
        material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203.017"]}
      />
      <mesh
        geometry={nodes.Pattern2D_4474558001.geometry}
        material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203.018"]}
      />
      <mesh
        geometry={nodes.Pattern2D_4474558001_1.geometry}
        material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203.019"]}
      />
      <mesh
        geometry={nodes.Pattern2D_4474558001_2.geometry}
        material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203.020"]}
      />
      <mesh
        geometry={nodes.Pattern2D_4491756001.geometry}
        material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203.021"]}
      />
      <mesh
        geometry={nodes.Pattern2D_4491756001_1.geometry}
        material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203.022"]}
      />
      <mesh
        geometry={nodes.Pattern2D_4491756001_2.geometry}
        material={materials["Knit_Fleece_Terry Copy 1_FRONT_109203.023"]}
      /> */}
    </group>
  );
}

useGLTF.preload("/tee6.glb");
