/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 tee8.glb 
*/

import React, { useRef } from "react";
import {
  DragControls,
  Edges,
  Image,
  PerspectiveCamera,
  RenderTexture,
  useGLTF,
} from "@react-three/drei";

export function Tee8(props) {
  const { nodes, materials } = useGLTF("/tee8.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_3.geometry} material={materials.Body}>
        <meshPhysicalMaterial>
          <RenderTexture attach="map" generateMipmaps>
            <PerspectiveCamera
              makeDefault
              manual
              aspect={1 / 1}
              position={[0, -1, 4]}
            />
            <color attach="background" args={["orange"]} />

            <DragControls>
              <Image
                url="/123.png"
                opacity={1}
                // side={DoubleSide}
                segments={1}
              >
                <Edges
                  linewidth={3}
                  scale={1.01}
                  threshold={15} // Display edges only when the angle between two faces exceeds this value (default=15 degrees)
                  color="blue"
                />
              </Image>
            </DragControls>
          </RenderTexture>
        </meshPhysicalMaterial>
      </mesh>
      {/* <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.shortsleeve}
      /> */}
    </group>
  );
}

useGLTF.preload("/tee8.glb");
