/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 tshirt1.glb 
Author: Tabbuso (https://sketchfab.com/Tabbuso)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tshirt-5a21282b2e454d1696547148f617d3d0
Title: Tshirt
*/

import React, { useEffect, useRef, useState } from "react";
import {
  Box,
  Decal,
  TransformControls,
  useGLTF,
  useTexture,
} from "@react-three/drei";

export function Model(props) {
  const texture = useTexture("vite.svg");

  const meshRef = useRef();
  const decalRef = useRef();
  const [showDecal, setShowDecal] = useState(false);

  const updatePos = (p) => {
    decalRef.current.position.set(p.x, p.y, p.y);
  };

  useEffect(() => {
    if (meshRef.current) {
      setShowDecal(true);
    }
  }, [meshRef.current]);
  const { nodes, materials } = useGLTF("/tshirt1.glb");
  return (
    <Box>
      <group {...props} dispose={null} position={[0, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.039}>
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials.FABRIC_1_FRONT_4193}
            ref={meshRef}
            onPointerDown={(e) => updatePos(e.point)}
          >
            {/* <Decal
              mesh={meshRef.current}
              ref={decalRef}
              scale={1}
              debug
              map={texture}
            /> */}
          </mesh>
          <mesh
            geometry={nodes.Object_5.geometry}
            material={materials.FABRIC_1_FRONT_4193}
          />
          <mesh
            geometry={nodes.Object_6.geometry}
            material={materials.FABRIC_1_FRONT_4193}
          />
          <mesh
            geometry={nodes.Object_7.geometry}
            material={materials.FABRIC_1_FRONT_4193}
          />
          ``
        </group>
      </group>
    </Box>
  );
}

useGLTF.preload("/tshirt1.glb");
